name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  provision-vpc:
    name: Provision VPC
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply VPC
        working-directory: ./terraform-root/vpc
        run: |
          terraform init -input=false
          terraform apply -auto-approve

  provision-eks:
    name: Provision EKS
    needs: provision-vpc
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply EKS
        working-directory: ./terraform-root/eks
        run: |
          terraform init -input=false
          terraform apply -auto-approve

  provision-github-runner:
    name: Provision GitHub Runner
    needs: provision-eks
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply GitHub Runner
        working-directory: ./terraform-root/github-runner
        run: |
          terraform init -input=false
          terraform apply -auto-approve
